### ISSUE TITLE
执行SSD 目标检测样例  ./run.sh出现报错

### ISSUE THREAD

**Issue by xiaocai506** [Cambricon/CNStream#111]
环境：docker 宿主机：centos 7.5

错误日志：
(* Note: Performance info of pipeline is slightly delayed compared to that of each stream.)
Pipeline :      -- [frame count]: 0, [processing time(s)]:   0.000000, [fps]:    0.0
[mjpeg @ 0x7fb7b8001d80] Changeing bps to 8
I1029 11:11:09.790115 54347 easy_infer.cpp:78] Init inference context, batch size: 1 device id: 0
I1029 11:11:09.817857 54347 easy_infer.cpp:96] Create MLU task queue from runtime context
I1029 11:11:09.818697 54347 resize_and_colorcvt.cpp:178] Init ResizeAndConvert Operator, [batchsize: 16], [core_number: 16].
I1029 11:11:10.286540 54354 resize_and_colorcvt.cpp:278] MluTaskQueue has not been set, MluResizeConvertOp will create a new one
**2020-10-29 11:11:10.287249: [cnrtError] [54354] [Card : 0] mluLaunchKernel fail.
2020-10-29 11:11:10.287352: [cnrtError] [54354] [Card : 0] fail to lanuch kernel.
2020-10-29 11:11:10.287449: [cnrtError] [54354] [Card : 0] for more information, please use core dump analysis tools.**
E1029 11:11:10.287614 54354 resize_and_colorcvt.cpp:339] Resize convert failed. Info: 
E1029 11:11:10.288530 54354 resize_and_colorcvt.cpp:340] dst w, dst h: 300300
E1029 11:11:10.288703 54354 resize_and_colorcvt.cpp:341] keep aspect ratio: 0
E1029 11:11:10.288830 54354 resize_and_colorcvt.cpp:342] batchsize: 16
E1029 11:11:10.288945 54354 resize_and_colorcvt.cpp:344] y plane attr: 0x200000ffcad00000
uv plane attr: 0x200000ffcad10000
src w: 256
src h: 256
src stride: 256
crop x: 0
crop y: 0
crop w: 256
crop h: 256
E1029 11:11:10.289341 54354 resize_and_colorcvt.cpp:344] y plane attr: 0x200000ffcad20000
uv plane attr: 0x200000ffcad30000
src w: 256
src h: 256
src stride: 256
crop x: 0
crop y: 0
crop w: 256
crop h: 256
E1029 11:11:10.289731 54354 resize_and_colorcvt.cpp:344] y plane attr: 0x200000ffcad40000
uv plane attr: 0x200000ffcad50000
src w: 256
src h: 256
src stride: 256
crop x: 0
crop y: 0
crop w: 256
crop h: 256
E1029 11:11:10.290042 54354 resize_and_colorcvt.cpp:344] y plane attr: 0x200000ffcad60000
uv plane attr: 0x200000ffcad70000
src w: 256
src h: 256
src stride: 256
crop x: 0
crop y: 0
crop w: 256
crop h: 256
E1029 11:11:10.290398 54354 resize_and_colorcvt.cpp:344] y plane attr: 0x200000ffcaf00000
uv plane attr: 0x200000ffcaf10000
src w: 256
src h: 256
src stride: 256
crop x: 0
crop y: 0
crop w: 256
crop h: 256
E1029 11:11:10.290792 54354 resize_and_colorcvt.cpp:344] y plane attr: 0x200000ffcaf20000
uv plane attr: 0x200000ffcaf30000
src w: 256
src h: 256
src stride: 256
crop x: 0
crop y: 0
crop w: 256
crop h: 256
E1029 11:11:10.291182 54354 resize_and_colorcvt.cpp:344] y plane attr: 0x200000ffcaf40000
uv plane attr: 0x200000ffcaf50000
src w: 256
src h: 256
src stride: 256
crop x: 0
crop y: 0
crop w: 256
crop h: 256
E1029 11:11:10.291554 54354 resize_and_colorcvt.cpp:344] y plane attr: 0x200000ffcaf60000
uv plane attr: 0x200000ffcaf70000
src w: 256
src h: 256
src stride: 256
crop x: 0
crop y: 0
crop w: 256
crop h: 256
E1029 11:11:10.291894 54354 resize_and_colorcvt.cpp:344] y plane attr: 0x200000ffd5b00000
uv plane attr: 0x200000ffd5b10000
src w: 256
src h: 256
src stride: 256
crop x: 0
crop y: 0
crop w: 256
crop h: 256
E1029 11:11:10.292261 54354 resize_and_colorcvt.cpp:344] y plane attr: 0x200000ffd5b20000
uv plane attr: 0x200000ffd5b30000
src w: 256
src h: 256
src stride: 256
crop x: 0
crop y: 0
crop w: 256
crop h: 256
E1029 11:11:10.292698 54354 resize_and_colorcvt.cpp:344] y plane attr: 0x200000ffd5b40000
uv plane attr: 0x200000ffd5b50000
src w: 256
src h: 256
src stride: 256
crop x: 0
crop y: 0
crop w: 256
crop h: 256
E1029 11:11:10.293067 54354 resize_and_colorcvt.cpp:344] y plane attr: 0x200000ffd5b60000
uv plane attr: 0x200000ffd5b70000
src w: 256
src h: 256
src stride: 256
crop x: 0
crop y: 0
crop w: 256
crop h: 256
E1029 11:11:10.293460 54354 resize_and_colorcvt.cpp:344] y plane attr: 0x200000ffccd00000
uv plane attr: 0x200000ffccd10000
src w: 256
src h: 256
src stride: 256
crop x: 0
crop y: 0
crop w: 256
crop h: 256
E1029 11:11:10.293900 54354 resize_and_colorcvt.cpp:344] y plane attr: 0x200000ffccd20000
uv plane attr: 0x200000ffccd30000
src w: 256
src h: 256
src stride: 256
crop x: 0
crop y: 0
crop w: 256
crop h: 256
E1029 11:11:10.294277 54354 resize_and_colorcvt.cpp:344] y plane attr: 0x200000ffccd40000
uv plane attr: 0x200000ffccd50000
src w: 256
src h: 256
src stride: 256
crop x: 0
crop y: 0
crop w: 256
crop h: 256
E1029 11:11:10.294665 54354 resize_and_colorcvt.cpp:344] y plane attr: 0x200000ffccd60000
uv plane attr: 0x200000ffccd70000
src w: 256
src h: 256
src stride: 256
crop x: 0
crop y: 0
crop w: 256
crop h: 256
I1029 11:11:10.296166 54354 mlu_context.cpp:50] Destroy MLU task queue
E1029 11:11:10.296669 54354 inferencer.cpp:79] resize convert failed.
2020-10-29 11:11:10.297223: [cnrtError] [54405] [Card : 0] fail to lanuch kernel.
2020-10-29 11:11:10.297290: [cnrtError] [54405] [Card : 0] for more information, please use core dump analysis tools.
2020-10-29 11:11:10.297355: [cnrtError] [54405] [Card : 0] Invoke failed of index 0E1029 11:11:10.297410 54405 easy_infer.cpp:125] Invoke Runtime Context failed error code: 632028
terminate called after throwing an instance of 'edk::EasyInferError'
  what():  Invoke Runtime Context failed error code : 632028
*** Aborted at 1603969870 (unix time) try "date -d @1603969870" if you are using GNU date ***
PC: @     0x7fb83fb08387 __GI_raise
*** SIGABRT (@0xd430) received by PID 54320 (TID 0x7fb7897d2700) from PID 54320; stack trace: ***
    @     0x7fb841425630 (unknown)
    @     0x7fb83fb08387 __GI_raise
    @     0x7fb83fb09a78 __GI_abort
    @     0x7fb8404187d5 (unknown)
    @     0x7fb840416746 (unknown)
    @     0x7fb840416773 (unknown)
    @     0x7fb84046d105 (unknown)
    @     0x7fb84141dea5 start_thread
    @     0x7fb83fbd08dd __clone
./run.sh: line 35: 54320 Aborted                 (core dumped) $CURRENT_DIR/../bin/demo --data_path $CURRENT_DIR/files.list_image --src_frame_rate 30 --wait_time 0 --loop=false --raw_img_input=false --config_fname "$CURRENT_DIR/detection_config.json"

**Comment by xiaocai506** [comment]
是模型下载不完整

**Comment by Lefttyre** [comment]
具体的Neuware版本和Driver版本是多少？

**Comment by xiaocai506** [comment]
driver：neuware-mlu270-driver-4.4.4-1.x86_64.rpm
Neuware：neuware-mlu270-1.5.0.el7.x86_64.rpm

**Comment by xiaocai506** [comment]
> 具体的Neuware版本和Driver版本是多少？

driver：neuware-mlu270-driver-4.4.4-1.x86_64.rpm
Neuware：neuware-mlu270-1.5.0.el7.x86_64.rpm

**Comment by Lefttyre** [comment]
原生自带的模型为16core并行模型，测试板卡为FD卡，建议用单核模型运行http://video.cambricon.com/models/MLU270/yolov3/yolov3_8objs_1c1b_argb_270_v1.4.0.cambricon

**Comment by xiaocai506** [comment]
> 原生自带的模型为16core并行模型，测试板卡为FD卡，建议用单核模型运行http://video.cambricon.com/models/MLU270/yolov3/yolov3_8objs_1c1b_argb_270_v1.4.0.cambricon
> http://video.cambricon.com/models/MLU270/yolov3/label_map_8objs.txt

谢谢
