### ISSUE TITLE
Tracking 算法的FeatureMatch存在bug

### ISSUE THREAD

**Issue by YuxiangJohn** [Cambricon/CNStream#141]
在Track module，EasyTrack中，FeatureMatch算法，做update的时候，使用的FeatureMatchTrackObject的pos成员永远是第一帧的rect，这个rect需要在update的时候使用卡尔曼滤波kf的mean进行更新。

**Comment by MaxwellDing** [comment]
见easydk/src/easytrack/track_fm.cpp:306
`fm_p_->tracks_[i].pos = BoundingBox2Rect(to_tlwh(fm_p_->tracks_[i].kf->GetCurPos()));`
每次update都是有更新pos的

**Comment by YuxiangJohn** [comment]
> 见easydk/src/easytrack/track_fm.cpp:306
> `fm_p_->tracks_[i].pos = BoundingBox2Rect(to_tlwh(fm_p_->tracks_[i].kf->GetCurPos()));`
> 每次update都是有更新pos的
> 这个bug是easydk 2.4.0版本更新修复的

感谢~
