### ISSUE TITLE
CMake create makefile failed

### ISSUE THREAD

**Issue by chenxy1988** [Cambricon/CNStream#146]
Hi CNSt. team,

When I run "cmake -DCMAKE_TOOLCHAIN_FILE=${CNSTREAM_DIR}/cmake/cross-compile.cmake ${CNSTREAM_DIR}" , the error happens and output error message as below:
CMake Error at CMakeLists.txt:227 (find_package):
  By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SDL2", but
  CMake did not find one.

  Could not find a package configuration file provided by "SDL2" with any of
  the following names:

    SDL2Config.cmake
    sdl2-config.cmake

  Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
  "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
  provides a separate development package or SDK, be sure it has been
  installed.

Could you help to check whether something wrong with cmake rule or something missing in my environment?

Thanks

**Comment by Lefttyre** [comment]
So sorry about running into this issue. Please add `-DMLU=MLU220EDGE -DCNIS_WITH_CURL=OFF -Dbuild_display=OFF` to cmake command. Because SDL2 is used by Displayer module which only designed for X86 graphic desktop

**Comment by chenxy1988** [comment]
Thanks Lefttyre, I'll try it again. 
For future issues, may I rise a issue here or would you leave any way to contact with you or your company engineer?

Many thanks!
