### ISSUE TITLE
RTSP 推流访问

### ISSUE THREAD

**Issue by a1072619378** [Cambricon/CNStream#162]
### RTSP推流访问
 在运行CNStream/python/samples/python pycnstream_demo.py  例子，能够成功运行。但是现在想通过VLC播放器查看RTSP推流的视频，请问访问地址是多少?
我的访问地址是：rtsp://127.0.0.1:8554，在播放器上提示错误无法打开。
请问，rtsp的默认访问地址和访问方法是什么？

**Comment by Lefttyre** [comment]
访问地址会以log形式打印在屏幕上的，看看屏幕上的log。一般会是本机ip：port, port 默认是9554，不过这个例子在配置文件中配置了8554.  另外也可以用其他播放器比如ffplay试一下能不能播放
