### ISSUE TITLE
运行generate_file_list.sh 文件报错

### ISSUE THREAD

**Issue by a1072619378** [Cambricon/CNStream#163]
在CNStream/samples目录下的运行如下命令：
$ sh generate_file_list.sh 
提示：
generate_file_list.sh: 2: generate_file_list.sh: Bad substitution
generate_file_list.sh: 6: generate_file_list.sh: Syntax error: Bad for loop variable
这是咋回事呢？

**Comment by Lefttyre** [comment]
尝试用 ./generate_file_list.sh 或者 bash generate_file_list.sh 。
这个应该跟你环境的Linux shell有关系

**Comment by a1072619378** [comment]
非常感谢  ./generate_file_list.sh 或者 bash generate_file_list.sh 都可以成功运行起来。
