### ISSUE TITLE
缺少典型dockerfile文件

### ISSUE THREAD

**Issue by Lefttyre** [Cambricon/CNStream#3]
如果提供一个dockerfile，可以更好地帮助客户快速部署。

**Comment by st7109** [comment]
We have prepared dockerfile for you, for now, can't find proper channel to share to U. any good advice, please let us know.

**Comment by lijiansong** [comment]
这个repo好像只是把头文件和二进制的动态链接库开源了。并不是真正意义上的开源。
后期cnstream有彻底开源的打算吗？
