### ISSUE TITLE
[zdxf] sometimes the pipeline may crash when using mlu preprocess for the "object_ infer" module

### ISSUE THREAD

**Issue by lordrebel** [Cambricon/CNStream#47]
![微信图片_20200710100718](https://user-images.githubusercontent.com/12432469/87108564-326ad800-c295-11ea-91a9-65ea4f4d0232.png)

**Comment by lordrebel** [comment]
![微信图片_20200710100718](https://user-images.githubusercontent.com/12432469/87108621-4f9fa680-c295-11ea-8f96-a41a7a1e7b04.png)

**Comment by Lefttyre** [comment]
this should be

**Comment by Lefttyre** [comment]
this should be
